{% set name = "fps-contents" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_contents-{{ version }}.tar.gz
  sha256: 39cf98a206efe928fabbeed8cb88603666bd63d29fab01d4ac96dee630694c3f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1
    - watchfiles >=1.0.4,<2
    - sqlite-anyio >=0.2.0,<0.3.0
    - anyio >=3.6.2,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_contents

about:
  home: https://github.com/jupyter-server/jupyverse/plugins/contents
  summary: An FPS plugin for the contents API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/plugins/contents
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
