{% set name = "fps-contents" %}
{% set version = "0.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_contents-{{ version }}.tar.gz
  sha256: 6dd41bd3ff5b9ae9ce7a3e216bb0c4a49c65e668d302c84d53914f73a931967a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.13.0,<0.14.0
    - anyio >=4.9.0,<5

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_contents

about:
  home: https://github.com/jupyter-server/jupyverse/plugins/contents
  summary: An FPS plugin for the contents API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/plugins/contents
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
