{% set name = "fps-contents" %}
{% set version = "0.0.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_contents-{{ version }}.tar.gz
  sha256: d5af741c0de71a145ec9418a2d9d667611782bcad37e2579e17290f1d4199718

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fps >=0.0.8,<1
    - fps-auth-base <1
    - anyio >=3,<4
    - watchfiles >=0.16.1,<1
    - aiosqlite >=0.17.0,<1
    - anyio>=3.6.2,<4

test:
  imports:
    - fps_contents

about:
  home: https://github.com/jupyter-server/jupyverse/plugins/contents
  summary: An FPS plugin for the contents API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/plugins/contents
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
