{% set name = "fps-contents" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_contents-{{ version }}.tar.gz
  sha256: 0060136415c0a2e6abcf632aabfbd8be3382f05cd74e35a8fb144372913852ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8
    - fps-auth
    - anyio

test:
  imports:
    - fps_contents

about:
  home: https://github.com/jupyter-server/jupyverse/plugins/contents
  summary: An FPS plugin for the contents API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/plugins/contents
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
