{% set name = "fps-contents" %}
{% set version = "0.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_contents-{{ version }}.tar.gz
  sha256: d01122c7157a8c2daa6e59e1feee5efff265f21c06121dea8399e7cdd9669844

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.12.0,<0.13.0
    - anyio >=3.6.2,<5

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_contents

about:
  home: https://github.com/jupyter-server/jupyverse/plugins/contents
  summary: An FPS plugin for the contents API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/plugins/contents
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
